---
tags: [SOAP]
projects: [spring-ws]
---
:spring_version: current
:spring_boot_version: 1.3.3.RELEASE
:spring_ws_version: 2.0
:Controller: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Controller.html
:DispatcherServlet: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/servlet/DispatcherServlet.html
:SpringApplication: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html
:ResponseBody: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/ResponseBody.html
:Endpoint: http://docs.spring.io/spring-ws/sites/{spring_ws_version}/apidocs/org/springframework/ws/server/endpoint/annotation/Endpoint.html
:PayloadRoot: http://docs.spring.io/spring-ws/sites/{spring_ws_version}/apidocs/org/springframework/ws/server/endpoint/annotation/PayloadRoot.html
:RequestPayload: http://docs.spring.io/spring-ws/sites/{spring_ws_version}/apidocs/org/springframework/ws/server/endpoint/annotation/RequestPayload.html
:ResponsePayload: http://docs.spring.io/spring-ws/sites/2.0/apidocs/org/springframework/ws/server/endpoint/annotation/ResponsePayload.html
:MessageDispatcherServlet: http://docs.spring.io/spring-ws/sites/2.0/apidocs/org/springframework/ws/transport/http/MessageDispatcherServlet.html
:DefaultMethodEndpointAdapter: http://docs.spring.io/spring-ws/sites/2.0/apidocs/org/springframework/ws/server/endpoint/adapter/DefaultMethodEndpointAdapter.html
:ApplicationContext: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/context/ApplicationContext.html
:DefaultWsdl11Definition: http://docs.spring.io/spring-ws/sites/2.0/apidocs/org/springframework/ws/wsdl/wsdl11/DefaultWsdl11Definition.html
:XsdSchema: http://docs.spring.io/spring-ws/sites/2.0/apidocs/org/springframework/xml/xsd/XsdSchema.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-soap-service

This guide walks you through the process of creating a SOAP-based web service server with Spring.

== What you'll build

You will build a server that exposes data from various European countries using a WSDL-based SOAP web service.

NOTE: To simplify the example, you will use hardcoded data for the United Kingdom, Spain and Poland.


== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]



[[initial]]
== Add Spring-WS dependency

The project you create needs to include `spring-ws-core` as a dependency in your build file as well as wsdl4j.

For maven:
[source,xml,indent=0]
----
include::complete/pom.xml[tags=springws]
----

For gradle:
[source,java,indent=0]
----
include::complete/build.gradle[tags=dependencies]
----

== Create an XML schema to define the domain

The web service domain is defined in an XML schema file (XSD) that Spring-WS will export automatically as a WSDL.

Create an XSD file with operations to return a country's **name**, **population**, **capital** and **currency**:

`src/main/resources/countries.xsd`
[source,xml,indent=0]
----
include::complete/src/main/resources/countries.xsd[]
----

== Generate domain classes based on an XML schema

The next step is to generate Java classes from the XSD file. The right approach is do this automatically during build time using a maven or gradle plugin.

Plugin configuration for maven:

[source,xml,indent=0]
----
include::complete/pom.xml[tags=xsd]
----

Generated classes are placed in `target/generated-sources/jaxb/` directory.

To do the same with gradle, first you need to configure JAXB in your build file:

[source,java,indent=0]
----
include::complete/build.gradle[tags=jaxb]
----

NOTE: The build file above has `tag` and `end` comments. This is to make it easier to extract bits of it into this guide for more detailed explanation. These comments aren't needed in your own build file.

Next step is to add task `genJaxb` used by gradle to generate Java classes:

[source,java,indent=0]
----
include::complete/build.gradle[tags=xsd]
----

As gradle does not have a JAXB plugin (yet), it involves an ant task, which makes it a bit more complex than in maven.

In both cases, the JAXB domain object generation process has been wired into the build tool’s lifecycle so there are no extra steps to run.

== Create country repository

In order to provide data to the web service, create a country repository. In this guide you create a dummy country repository implementation with hardcoded data.

[source,java]
----
include::complete/src/main/java/hello/CountryRepository.java[]
----

== Create country service endpoint

To create a service endpoint, you only need a link:/understanding/POJO[POJO] with a few Spring WS annotations to handle the incoming SOAP requests.

[source,java]
----
include::complete/src/main/java/hello/CountryEndpoint.java[]
----

{Endpoint}[`@Endpoint`] registers the class with Spring WS as a potential candidate for processing incoming SOAP messages.

{PayloadRoot}[`@PayloadRoot`] is then used by Spring WS to pick the handler method based on the message's **namespace** and **localPart**.

{RequestPayload}[`@RequestPayload`] indicates that the incoming message will be mapped to the method's `request` parameter.

The {ResponsePayload}[`@ResponsePayload`] annotation makes Spring WS map the returned value to the response payload.

NOTE: In all of these chunks of code, the `io.spring.guides` classes will report compile-time errors in your IDE unless you have run the task to generate the domain classes based on the WSDL.

== Configure web service beans

Create a new class with Spring WS related beans configuration:

[source,java]
----
include::complete/src/main/java/hello/WebServiceConfig.java[]
----

* Spring WS uses a different servlet type for handling SOAP messages: {MessageDispatcherServlet}[`MessageDispatcherServlet`]. It is important to inject and set {ApplicationContext}[`ApplicationContext`] to {MessageDispatcherServlet}[`MessageDispatcherServlet`]. Without that, Spring WS will not detect Spring beans automatically. 
* By naming this bean `messageDispatcherServlet`, it does not http://docs.spring.io/spring-boot/docs/{spring_boot_version}/reference/htmlsingle/#howto-switch-off-the-spring-mvc-dispatcherservlet[replace Spring Boot's default `DispatcherServlet` bean].
* {DefaultMethodEndpointAdapter}[`DefaultMethodEndpointAdapter`] configures annotation driven Spring WS programming model. This makes it possible to use the various annotations like {Endpoint}[`@Endpoint`] mentioned earlier.
* {DefaultWsdl11Definition}[`DefaultWsdl11Definition`] exposes a standard WSDL 1.1 using {XsdSchema}[`XsdSchema`]

It's important to notice that you need to specify bean names for {MessageDispatcherServlet}[`MessageDispatcherServlet`] and {DefaultWsdl11Definition}[`DefaultWsdl11Definition`]. Bean names determine the URL under which web service and the generated WSDL file is available. In this case, the WSDL will be available under `http://<host>:<port>/ws/countries.wsdl`.

This configuration also uses the WSDL location servlet transformation `servlet.setTransformWsdlLocations(true)`. If you visit http://localhost:8080/ws/countries.wsdl, the `soap:address` will have the proper address. If you instead
visit the WSDL from the public facing IP address assigned to your machine, you will see that address instead.

== Make the application executable

Although it is possible to package this service as a traditional link:/understanding/WAR[WAR] file for deployment to an external application server, the simpler approach demonstrated below creates a standalone application. You package everything in a single, executable JAR file, driven by a good old Java `main()` method. Along the way, you use Spring's support for embedding the link:/understanding/Tomcat[Tomcat] servlet container as the HTTP runtime, instead of deploying to an external instance.


`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

`@SpringBootApplication` is a convenience annotation that adds all of the following:
    
- `@Configuration` tags the class as a source of bean definitions for the application context.
- `@EnableAutoConfiguration` tells Spring Boot to start adding beans based on classpath settings, other beans, and various property settings.
- Normally you would add `@EnableWebMvc` for a Spring MVC app, but Spring Boot adds it automatically when it sees **spring-webmvc** on the classpath. This flags the application as a web application and activates key behaviors such as setting up a `DispatcherServlet`.
- `@ComponentScan` tells Spring to look for other components, configurations, and services in the the `hello` package, allowing it to find the `HelloController`.

The `main()` method uses Spring Boot's `SpringApplication.run()` method to launch an application. Did you notice that there wasn't a single line of XML? No **web.xml** file either. This web application is 100% pure Java and you didn't have to deal with configuring any plumbing or infrastructure.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]


Logging output is displayed. The service should be up and running within a few seconds.


== Test the application

Now that the application is running, you can test it. Create a file `request.xml` containing the following SOAP request:

[source,xml]
----
include::complete/request.xml[]
----

The are a few options when it comes to testing the SOAP interface. You can use something like http://www.soapui.org[SoapUI] or just use command line tools if you are on a *nix/Mac system as shown below.

[source,plain]
----
$ curl --header "content-type: text/xml" -d @request.xml http://localhost:8080/ws
----

As a result you should see this response:

[source,xml]
----
<?xml version="1.0"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header/>
  <SOAP-ENV:Body>
    <ns2:getCountryResponse xmlns:ns2="http://spring.io/guides/gs-producing-web-service">
      <ns2:country>
        <ns2:name>Spain</ns2:name>
        <ns2:population>46704314</ns2:population>
        <ns2:capital>Madrid</ns2:capital>
        <ns2:currency>EUR</ns2:currency>
      </ns2:country>
    </ns2:getCountryResponse>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
----

NOTE: Odds are that the output will be a compact XML document instead of the nicely formatted one shown above. If you have xmllib2 installed on your system, you can `curl <args above> > output.xml | xmllint --format output.xml` 
see the results formatted nicely.

== Summary

Congratulations! You've developed a SOAP-based service using Spring Web Services.




include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]

