:spring_version: current
:spring_boot_version: current
:spring_ws_api: https://docs.spring.io/spring-ws/docs/current/api
:Endpoint: {spring_ws_api}/org/springframework/ws/server/endpoint/annotation/Endpoint.html
:PayloadRoot: {spring_ws_api}/org/springframework/ws/server/endpoint/annotation/PayloadRoot.html
:RequestPayload: {spring_ws_api}/org/springframework/ws/server/endpoint/annotation/RequestPayload.html
:ResponsePayload: {spring_ws_api}/org/springframework/ws/server/endpoint/annotation/ResponsePayload.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-soap-service

This guide walks you through the process of creating a SOAP-based web service server with Spring.

== What You Will build

You will build a server that exposes data from various European countries by using a
WSDL-based SOAP web service.

NOTE: To simplify the example, you will use hardcoded data for the United Kingdom, Spain, and Poland.

== What You Need

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/how_to_complete_this_guide.adoc[]

[[scratch]]
== Starting with Spring Initializr

You can use this https://start.spring.io/#!type=gradle-project&groupId=com.example&artifactId=producing-web-service&name=producing-web-service&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.producing-web-service&dependencies=web,web-services[pre-initialized project] and click Generate to download a ZIP file. This project is configured to fit the examples in this tutorial.

To manually initialize the project:

. Navigate to https://start.spring.io.
This service pulls in all the dependencies you need for an application and does most of the setup for you.
. Choose either Gradle or Maven and the language you want to use. This guide assumes that you chose Java.
. Click *Dependencies* and select *Spring Web* and *Spring Web Services*.
. Click *Generate*.
. Download the resulting ZIP file, which is an archive of a web application that is configured with your choices.

NOTE: If your IDE has the Spring Initializr integration, you can complete this process from your IDE.


[[initial]]
== Create an XML Schema to Define the Domain

The web service domain is defined in an XML schema file (XSD) that Spring-WS will
automatically export as a WSDL.

Create an XSD file with operations to return a country's `name`, `population`, `capital`,
and `currency`. The following listing (from `src/main/resources/wsdl/countries.xsd`) shows the
necessary XSD file:

[source,xml,indent=0]
----
include::complete/src/main/resources/wsdl/countries.xsd[]
----

== Generate Domain Classes Based on an XML Schema

The next step is to generate Java classes from the XSD file. The right approach is to do
this automatically during build time by using a Maven or Gradle plugin.

The following listing shows the necessary plugin configuration for Maven:

[source,xml,indent=0]
----
include::complete/pom.xml[tags=xsd]
----

Generated classes are placed in the `target/generated-sources/jaxb/` directory.

To do the same with Gradle, you can declare a new plugin in the `plugin` section :

[source,java,indent=0]
----
include::complete/build.gradle[tags=xjcplugin]
----

And then configure it to point to the XSD files location:

[source,java,indent=0]
----
include::complete/build.gradle[tags=xjcconfig]
----

In both cases, the JAXB domain object generation process has been wired into the build
tool’s lifecycle, so there are no extra steps to run.

== Create Country Repository

In order to provide data to the web service, create a country repository. In this guide,
you create a dummy country repository implementation with hardcoded data. The following
listing (from `src/main/java/com/example/producingwebservice/CountryRepository.java`)
shows how to do so:

[source,java]
----
include::complete/src/main/java/com/example/producingwebservice/CountryRepository.java[]
----

== Create Country Service Endpoint

To create a service endpoint, you need only a POJO with a few Spring WS annotations to
handle the incoming SOAP requests. The following listing (from
`src/main/java/com/example/producingwebservice/CountryEndpoint.java`) shows such a class:

[source,java]
----
include::complete/src/main/java/com/example/producingwebservice/CountryEndpoint.java[]
----

The {Endpoint}[`@Endpoint`] annotation registers the class with Spring WS as a potential
candidate for processing incoming SOAP messages.

The {PayloadRoot}[`@PayloadRoot`] annotation is then used by Spring WS to pick the handler
method, based on the message's `namespace` and `localPart`.

The {RequestPayload}[`@RequestPayload`] annotation indicates that the incoming message
will be mapped to the method's `request` parameter.

The {ResponsePayload}[`@ResponsePayload`] annotation makes Spring WS map the returned
value to the response payload.

NOTE: In all of these chunks of code, the `io.spring.guides` classes will report
compile-time errors in your IDE unless you have run the task to generate the domain
classes based on the WSDL.


== Expose the web service

Spring Boot will automatically load and expose your WSDL and XSD definitions the required infrastructure for exposing
the service definitions. In this case, the WSDL will be available under `http://<host>:<port>/services/countries.wsdl`.

[source,properties]
----
include::complete/src/main/resources/application.properties[]
----

By default, they will be exposed on the `"/services"` HTTP endpoint, but this can be customized
with the `spring.webservices.path` property.

== Test the Application

Now that the application is running, you can test it. Create a file called `request.xml`
that contains the following SOAP request:

====
[source,xml]
----
include::complete/request.xml[]
----
====

The are a few options when it comes to testing the SOAP interface. You can use something
similar to http://www.soapui.org[SoapUI] or use command-line tools if you are on a
*nix/Mac system. The following example uses curl from the command line:

[source,bash]
----
# Use data from file
$ curl --header "Content-Type: text/xml" -d @request.xml http://localhost:8080/services | xmllint --format
----

As a result, you should see the following response:

[source,xml]
----
<?xml version="1.0"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header/>
  <SOAP-ENV:Body>
    <ns2:getCountryResponse xmlns:ns2="https://spring.io/guides/gs-producing-web-service">
      <ns2:country>
        <ns2:name>Spain</ns2:name>
        <ns2:population>46704314</ns2:population>
        <ns2:capital>Madrid</ns2:capital>
        <ns2:currency>EUR</ns2:currency>
      </ns2:country>
    </ns2:getCountryResponse>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
----


== Summary

Congratulations! You have developed a SOAP-based service with Spring Web Services.

== See Also

The following guides may also be helpful:

* https://spring.io/guides/gs/consuming-web-service/[Consuming a SOAP web service]
* https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/footer.adoc[]
